### PR TITLE
Modify Callback API to allow asynchronous incoming requests

### PR DESCRIPTION
**Pull request by bbengfort**
- [x] protocol buffer updates from TRV-112
- [x] adds TRISA generic data protobufs 

/assign @skymeyer

### CODE REVIEW

**Comment by skymeyer** [comment]
/ok-to-test
/approve
/hold

Awaiting deployment update before merging.

**Comment by skymeyer** [comment]
@bbengfort can you review the import of that new proto, bazel will need some reference for that.

**Comment by bbengfort** [comment]
@skymeyer I think that sorted it

**Comment by skymeyer** [comment]
ty @bbengfort !
/unhold

**Pull request merged**
